// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Toaster } from "sonner";
import { Toaster as UIToaster } from "@/components/ui/toaster";
import AuthenticatedLayout from "@/components/AuthenticatedLayout";
import { ErrorBoundary } from "@/components/ErrorBoundary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "OBREASY",
  description: "Controle completo da sua obra - Gestão financeira, profissionais e relatórios em tempo real",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "OBREASY",
  },
  verification: {
    google: "cblxEr4OaQALgtBTkeRadx1sjtV8xPeQKAtCouPGmyI",
  },
  formatDetection: {
    telephone: false,
  },
  icons: {
    icon: [
      { url: "https://blietvjzchjrzbmkitha.supabase.co/storage/v1/object/public/images/WhatsApp%20Image%202026-02-09%20at%2009.46.17.jpeg", type: "image/jpeg" },
      { url: "https://blietvjzchjrzbmkitha.supabase.co/storage/v1/object/public/images/WhatsApp%20Image%202026-02-09%20at%2009.46.17.jpeg", sizes: "192x192", type: "image/jpeg" },
      { url: "https://blietvjzchjrzbmkitha.supabase.co/storage/v1/object/public/images/WhatsApp%20Image%202026-02-09%20at%2009.46.17.jpeg", sizes: "512x512", type: "image/jpeg" },
    ],
    apple: [
      { url: "https://blietvjzchjrzbmkitha.supabase.co/storage/v1/object/public/images/WhatsApp%20Image%202026-02-09%20at%2009.46.17.jpeg", type: "image/jpeg" },
    ],
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: '#0B3064',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="lazyOnload" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#0B3064" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="OBREASY" />
        <link rel="apple-touch-icon" href="https://blietvjzchjrzbmkitha.supabase.co/storage/v1/object/public/images/WhatsApp%20Image%202026-02-09%20at%2009.46.17.jpeg" />
        <Script id="register-sw" strategy="afterInteractive">
          {`
            if ('serviceWorker' in navigator) {
              window.addEventListener('load', function() {
                navigator.serviceWorker.register('/sw.js').then(
                  function(registration) {
                    console.log('ServiceWorker registrado com sucesso:', registration.scope);
                  },
                  function(err) {
                    console.log('ServiceWorker falhou ao registrar:', err);
                  }
                );
              });
            }
          `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        <ErrorBoundary>
          <AuthenticatedLayout>
            {children}
          </AuthenticatedLayout>
          <Toaster position="top-right" richColors />
          <UIToaster />
        </ErrorBoundary>
      </body>
    </html>
  );
}
