// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Toaster } from "sonner";
import { Toaster as UIToaster } from "@/components/ui/toaster";
import AuthenticatedLayout from "@/components/AuthenticatedLayout";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import QueryProvider from "@/components/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://www.obreasy.com.br";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Obreasy | Aplicativo de Controle e Gestão de Obras",
    template: "%s | Obreasy",
  },
  description:
    "Aplicativo para controle e gestão de obras. Acompanhe orçamento, gastos, profissionais e diário da obra num só lugar, pelo celular ou pelo computador.",
  keywords: [
    "aplicativo para controle de obras",
    "controle de obras",
    "gestão de obras",
    "controle de gastos de obra",
    "aplicativo para reforma",
    "software de gestão de obras",
    "diário de obra",
    "orçamento de obra",
  ],
  applicationName: "Obreasy",
  category: "business",
  manifest: "/manifest.json",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "pt_BR",
    url: SITE_URL,
    siteName: "Obreasy",
    title: "Obreasy | Aplicativo de Controle e Gestão de Obras",
    description:
      "Acompanhe orçamento, gastos, profissionais e diário da obra num só lugar, pelo celular ou pelo computador.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Obreasy | Aplicativo de Controle e Gestão de Obras",
    description:
      "Acompanhe orçamento, gastos, profissionais e diário da obra num só lugar, pelo celular ou pelo computador.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "OBREASY",
  },
  verification: {
    google: "cblxEr4OaQALgtBTkeRadx1sjtV8xPeQKAtCouPGmyI",
  },
  formatDetection: {
    telephone: false,
  },
  // Sem override aqui, o Next serve icon.tsx / apple-icon.tsx (PNG gerado no
  // próprio domínio). Antes apontava para um JPEG solto no bucket do Supabase.
};

// Dados estruturados no HTML servido pelo servidor, não injetados por JS: o
// Google processa com atraso o que só aparece depois da hidratação.
const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "SoftwareApplication",
      "@id": `${SITE_URL}/#app`,
      name: "Obreasy",
      applicationCategory: "BusinessApplication",
      applicationSubCategory: "Gestão de Obras",
      operatingSystem: "iOS, Android, Web",
      inLanguage: "pt-BR",
      url: SITE_URL,
      description:
        "Aplicativo para controle e gestão de obras. Acompanhe orçamento, gastos, profissionais e diário da obra num só lugar.",
      featureList: [
        "Controle de orçamento e gastos da obra",
        "Gestão de profissionais e pagamentos",
        "Diário de obra com fotos",
        "Relatórios em PDF",
        "Custo por metro quadrado",
        "Controle de recebimentos",
      ],
      offers: [
        {
          "@type": "Offer",
          name: "Essencial",
          price: "29.90",
          priceCurrency: "BRL",
          category: "subscription",
          url: `${SITE_URL}/dashboard/plano`,
        },
        {
          "@type": "Offer",
          name: "Profissional",
          price: "49.90",
          priceCurrency: "BRL",
          category: "subscription",
          url: `${SITE_URL}/dashboard/plano`,
        },
      ],
      publisher: { "@id": `${SITE_URL}/#organization` },
    },
    {
      "@type": "Organization",
      "@id": `${SITE_URL}/#organization`,
      name: "Obreasy",
      url: SITE_URL,
      email: "suporte@obreasy.com.br",
      contactPoint: {
        "@type": "ContactPoint",
        contactType: "customer support",
        email: "suporte@obreasy.com.br",
        availableLanguage: "Portuguese",
      },
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      url: SITE_URL,
      name: "Obreasy",
      inLanguage: "pt-BR",
      publisher: { "@id": `${SITE_URL}/#organization` },
    },
  ],
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: '#0B3064',
  viewportFit: 'cover',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="lazyOnload" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#0B3064" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="OBREASY" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
        />
        <Script id="register-sw" strategy="afterInteractive">
          {`
            if ('serviceWorker' in navigator) {
              window.addEventListener('load', function() {
                navigator.serviceWorker.register('/sw.js').then(
                  function(registration) {
                    console.log('ServiceWorker registrado com sucesso:', registration.scope);
                  },
                  function(err) {
                    console.log('ServiceWorker falhou ao registrar:', err);
                  }
                );
              });
            }
          `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        <ErrorBoundary>
          <QueryProvider>
            <AuthenticatedLayout>
              {children}
            </AuthenticatedLayout>
            <Toaster position="top-right" richColors />
            <UIToaster />
          </QueryProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
